const testTokens = {
  adminTestToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MywibmFtZSI6Im1pa2Uga3J6eXpld3NraSIsImV4cCI6MTUyMjAwODM4OCwiaWF0IjoxNTE2ODI3OTg4fQ.eJn7I-7wibxOLnSOEUwd9SN6-NlOgQjHVOVsfsLqePU',
  managerTestToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NiwibmFtZSI6IkNocmlzdGluZSBaaG91IiwidXNlcl9ncm91cCI6Im1hbmFnZXIiLCJleHAiOjE1MjM3MTkzMjUsImlhdCI6MTUxODUzODkyNX0.R48oPTOQcJGPHQDzoeQ4Em7hIm1bNyXLaL8_ccXrpyU',
  noobTestToken: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NCwibmFtZSI6Im1pa2Ugd2F6b3dza2kiLCJleHAiOjE1MjIwMDgzODgsImlhdCI6MTUxNjgyNzk4OH0.faHRtk9TtsqCf5lQSzWgaNcf5SX-Gm-_LYsa2X9XoOk',
};

module.exports = testTokens;
