language: node_js
node_js:
- '8'
services:
- mysql
before_script:
- yes | cp -rf ./server/config.travis.js ./server/config.js
- mysql -u root -e "CREATE DATABASE meals_test"
addons:
  ssh_known_hosts: '152.3.53.74'
after_success:
- openssl aes-256-cbc -K $encrypted_95a91f9e7702_key -iv $encrypted_95a91f9e7702_iv
  -in hm-staging.enc -out secret -d
- eval \"$(ssh-agent -s)\"
- ssh-add secret
- ssh vcm@152.3.53.74 'cd meals && npm run deploy'
