INSERT INTO Users (id, name, hash, salt, user_group) VALUES (1, 'Bill', 'hash', 'salt', 'admin');
INSERT INTO Users (id, name, hash, salt, user_group) VALUES (2, 'Eric', 'hash', 'salt', 'noob');
INSERT INTO Vendors (id, name, contact, code) VALUES (1, 'Duke', 'contact', 'code');
INSERT INTO Storages (id, name, capacity) VALUES (1, 'freezer', 20);
INSERT INTO Storages (id, name, capacity) VALUES (2, 'refrigerator', 20);
INSERT INTO Ingredients (id, name, storage_id) VALUES (1, 'poop', 1);
INSERT INTO Ingredients (id, name, storage_id) VALUES (2, 'beans', 1);
INSERT INTO Ingredients (id, name, storage_id) VALUES (3, 'boop', 1);
INSERT INTO VendorsIngredients (id, ingredient_id, package_type, price, vendor_id) VALUES (1, 1, 'sack', 10, 1);
INSERT INTO VendorsIngredients (id, ingredient_id, package_type, price, vendor_id) VALUES (2, 2, 'pail', 20, 1);
INSERT INTO VendorsIngredients (id, ingredient_id, package_type, price, vendor_id) VALUES (3, 3, 'pail', 30, 1);
INSERT INTO Inventories (id, ingredient_id, storage_weight, total_weight) VALUES(1, 1, 5, 10);
INSERT INTO Inventories (id, ingredient_id, storage_weight, total_weight) VALUES (2, 2, 15, 20);
INSERT INTO Logs (id, user_id, vendor_ingredient_id, quantity) VALUES (1, 1, 1, 18);
INSERT INTO Logs (id, user_id, vendor_ingredient_id, quantity) VALUES (2, 1, 3, 5);
INSERT INTO SpendingLogs (id, ingredient_id, total, consumed) VALUES (1, 1, 100, 50);
