INSERT INTO Users VALUES(1, 'Bill', 'hash', 'salt', 'admin');
INSERT INTO Users VALUES(2, 'Eric', 'hash', 'salt', 'noob');
INSERT INTO Vendors VALUES(1, 'Duke', 'contact', 'code');
INSERT INTO Storages VALUES(1, 'freezer', 10);
INSERT INTO Storages VALUES(2, 'refrigerator', 20);
INSERT INTO Ingredients VALUES(1, 'poop', 1);
INSERT INTO Ingredients VALUES(2, 'beans', 1);
INSERT INTO VendorsIngredients VALUES(1, 1, 'sack', 10, 1);
INSERT INTO VendorsIngredients VALUES(2, 2, 'pail', 20, 1);
INSERT INTO Inventories VALUES(1, 1, 5, 10);
INSERT INTO Inventories VALUES(2, 2, 15, 20);
INSERT INTO Logs (id, user_id, vendor_ingredient_id, quantity) VALUES (1, 1, 1, 18);
